version: "3.7"

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  notebook:
    build: ./libs
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    links:
      - cassandra
