version: "3.7"

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  notebook:
    build: .
    volumes:
      - ../notebooks/:/app
      - ../data/:/app/data
      - ../src/:/app/src
    ports:
      - "8888:8888"
    links:
      - cassandra
