---
    name: Checks

    on: [push]

    jobs:
      test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Test
            run: docker-compose run --rm notebook sh -c "python3 -m coverage run --rcfile=.coveragerc -m unittest discover && coverage report && coverage html"
          - name: Lint
            run: docker-compose run --rm notebook sh -c "flake8"
